name: database

on: 
  push: 
    branches:
      - master 

jobs:
  integration-test:
    runs-on: ubuntu-latest

    service:
      paradedb:
        image: paradedb/paradedb:latest
        container_name: database
        ports:
          - "5000:5432"
        volumes: 
          - pgvector_data:/var/lib/postgresql
        
        environment:
        POSTGRES_PASSWORD: "5515"
        POSTGRES_USER: AHMED
        POSTGRES_DB: SecondMind
        networks:
          - Backend

        restart: always



    steps:
      - name: checkout
        uses: actions/checkout@v6
      
      - name: install python
        uses: actions/setup-python@v7.0.0
        with:  
          python-version: "3.12.9"

      - name: install dependencies
        run: | 
          pip install -r requirements.txt


      - name: connection test
        env:
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: pytest ./testing/integration_testing/connection_testing.py

