name: database

on: 
  push: 
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
      
      - name: install python
        uses: actions/setup-python@v7.0.0
        with:  
          python-version: "3.12.9"

      - name: install dependencies
        run: | 
          pip install -r .\requirements.txt


      - name: connection
        run: pytest ./testing/integration_testing/connection_testing.py
